Anup Gurung (ACE080BCT013)

Lab 3: PyTorch Fundamentals


->Objectives:
  1.To understand the basic concepts of PyTorch and its role in machine learning and deep learning applications.
  2.To create and manipulate tensors using various PyTorch operations and functions.
  3.To learn automatic differentiation (Autograd) for computing gradients during model training.
  4.To build and train simple neural network models using PyTorch modules, loss functions, and optimizers.
  5.To gain practical experience in data handling, model training, and evaluation using PyTorch's built-in tools and workflows.

Theory

PyTorch is an open-source deep learning framework developed by Meta. It provides efficient tensor computation with GPU acceleration and supports automatic differentiation, making it a powerful tool for building, training, and deploying machine learning and deep learning models. Due to its flexibility, dynamic computation graph, and user-friendly programming interface, PyTorch is widely adopted by researchers, students, and developers.

Introduction to Scalars, Vectors, Matrices, and Tensors

In mathematics and machine learning, data is represented using different numerical structures known as scalars, vectors, matrices, and tensors.

A scalar is a single numerical value with no dimensions, such as 5 or 10. A vector is a one-dimensional collection of values arranged in a sequence, for example, [1, 2, 3]. A matrix is a two-dimensional arrangement of numbers organized into rows and columns, commonly used to represent tabular data. A tensor is a generalized form of these structures that can have multiple dimensions. Scalars, vectors, and matrices are all special cases of tensors.

Tensors serve as the fundamental data structure in PyTorch and play a crucial role in machine learning and deep learning applications. They enable efficient storage and processing of various types of data, including images, text, audio, and model parameters.

The primary purpose of tensors is to represent data numerically so that machine learning algorithms can perform computations effectively. For example, a color image can be represented as a tensor with the shape [3, 224, 224], where 3 represents the color channels (Red, Green, and Blue), 224 represents the image height in pixels, and 224 represents the image width in pixels. In this example, the tensor has three dimensions corresponding to the color channels, height, and width of the image.

Tensor Data Types in PyTorch
torch.int8 – 8-bit integer data type used for storing values ranging from -128 to 127.
torch.int16 – 16-bit integer data type suitable for storing small integer values.
torch.int32 – 32-bit integer data type commonly used for standard integer operations.
torch.int64 (torch.long) – 64-bit integer data type used for storing large integer values.
torch.float16 – 16-bit floating-point data type designed for low-precision computations and memory efficiency.
torch.float32 (torch.float) – 32-bit floating-point data type and the default floating-point type in PyTorch.
torch.float64 (torch.double) – 64-bit floating-point data type that provides higher numerical precision.
torch.bool – Boolean data type used to represent logical values, either True or False.
Common Tensor Operations

PyTorch provides a wide range of tensor operations that are essential for mathematical computations and neural network training. Some of the most frequently used operations include:

Addition
Subtraction
Element-wise Multiplication
Division
Matrix Multiplication



In [ ]:
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu132

Looking in indexes: https://download.pytorch.org/whl/cu132


In [3]:
# importing pytorch

import torch
torch.__version__
# creating scalar using tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


In [3]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [4]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


In [5]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


In [7]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [8]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [9]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.1284, 0.2094, 0.8549],
         [0.4238, 0.2421, 0.8020]]),
 torch.float32)

In [10]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [12]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [13]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [16]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [17]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [18]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3242, 0.3796, 0.3941, 0.9827],
        [0.3033, 0.2491, 0.5731, 0.8950],
        [0.1073, 0.0277, 0.8846, 0.4109]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tensor Operations

In [19]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [20]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [21]:
tensor

tensor([1, 2, 3])

In [22]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [23]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [24]:
tensor

tensor([-9, -8, -7])

In [25]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [26]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [27]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [1]:
import torch

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [2]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Finding the min, max, mean, sum, etc (aggregation)

In [33]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


Positional min/max

In [34]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


Change tensor datatype

In [35]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Reshaping

In [36]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [37]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

View

In [38]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [39]:
z = x.view(2,4)
z, z.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [40]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [41]:
x = torch.arange(6)

a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


That's the exact reason both functions exist: view() is a strict "reinterpret the existing memory" operation, while reshape() is a flexible "give me this shape, even if a copy is needed" operation.

Stack

 ->torch.stack(tensors, dim=0): Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

In [42]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [43]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])


Squeeze and Unsqueeze funtions.

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [44]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


permute

torch.permute() is used to rearrange the order of a tensor's dimensions (axes) without changing the underlying data values.

In [45]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

 Indexing

In [46]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [47]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


Pytorch Tensor to NumPy arrays and vice versa

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

->torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

->torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [48]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Tensors on GPU

In [52]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [53]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [54]:
# Count number of devices
torch.cuda.device_count()


1

In [55]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [56]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Discussion and Conclusion

In this lab, the basic concepts of PyTorch were studied, including scalars, vectors, matrices, tensors, tensor data types, tensor operations, and introductory deep learning workflows. Different tensor creation and manipulation techniques were performed to gain an understanding of how data is stored and processed within PyTorch. The lab also covered automatic differentiation and fundamental neural network concepts, highlighting how PyTorch streamlines model development and training through its flexible and efficient design.

The lab established a strong foundation in PyTorch by focusing on tensors, which serve as the framework's primary data structure, along with the various operations that can be performed on them. Through hands-on exercises, knowledge of tensor creation, manipulation, data type management, and basic neural network implementation was gained. Overall, the activities demonstrated that PyTorch is a versatile and easy-to-use framework for machine learning and deep learning applications, making it an important tool for the development of modern artificial intelligence systems.